### ISSUE TITLE
Tracing outside domain boundaries

### ISSUE THREAD

**Issue by henry2004y** [henry2004y/TestParticle.jl#10]
Handling the tracing outside the given mesh is a problem. Right now I set the field values outside the simulation domain to NaN. Although the ODE system itself is not stiff, when the tracked particles move outside the domain, the NaN values in the force terms will trigger instability detection of the ODE solvers.

Fortunately, the solver will automatically exit the loop when such error is detected, and in the solution object the final timestamp will be less than the tspan. We can use this to check those out-of-bound particles and plot accordingly. An example is given for a collection of ensemble tracing in the PIC box.

**Comment by TCLiuu** [comment]
> Currently, any point evaluated outside the domain boundary through `interpolate` is set to `NaN`. Older version set this to 0. Maybe the default settings are changed? If it automatically throws error, that's fine.

If `interpolate` can throw an error automatically, will `DifferentialEquation` catch the error, stop running and return those points already calculated?

**Comment by henry2004y** [comment]
I don't remember. You can test on it.

**Comment by henry2004y** [comment]
On [this page](https://diffeq.sciml.ai/stable/basics/common_solver_opts/), I found in the `solve` miscellaneous arguments section that `isoutofdomain` specifies a function `isoutofdomain(u,p,t) `where, when it returns true, it will reject the timestep. This fantastic callback method what we should use in general.

**Comment by henry2004y** [comment]
Closed via #54.
