### ISSUE TITLE
Guiding center tracing

### ISSUE THREAD

**Issue by henry2004y** [henry2004y/TestParticle.jl#169]
We may need a guiding center approximation solver.

One implementation from the PLUTO MHD code for the 1st order GCA equations is summarized [here](https://henry2004y.github.io/KeyNotes/contents/gc.html#classical-guiding-center-theory). This one is relativistic but does not use the Hamiltonian. The source code is not publicly available.

Relativistic tracer with multistep method in PLUTO: https://arxiv.org/abs/2212.08064

-----

The noncanonical Hamiltonian theory of guiding center equations can be found in #64 (or [here](https://henry2004y.github.io/KeyNotes/contents/gc.html#hamiltonian-theory-of-guiding-center-motion)). This one is theoretically more advanced, and maybe it is even easier to implement than the classical one.

**Comment by TCLiuu** [comment]
You can refer to the equations and review mentioned in #64. These equations from the Hamiltonian are more accurate than those classical equations.

**Comment by henry2004y** [comment]
Thank you for the reminder! At some point we need to add this feature.

**Comment by henry2004y** [comment]
I summarized one implementation from PLUTO MHD for the 1st order GCA equations [here](https://henry2004y.github.io/KeyNotes/contents/gc.html#first-order-solution-for-the-gca-equations-of-motion). This one does not use the Hamiltonian. The source code is not publicly available.
