### ISSUE TITLE
Normalization in trace_normalized!

### ISSUE THREAD

**Issue by Beforerr** [henry2004y/TestParticle.jl#199]
According to #117 , we could not trace electron with time going forward as the time normalization factor would be negative. I would suggest to normalize to element charge instead of particle charge. In that case, we could also trace different particle population.

**Comment by henry2004y** [comment]
You mean in the time normalization, there is a factor q which can be negative for electrons right?

**Comment by Beforerr** [comment]
> You mean in the time normalization, there is a factor q which can be negative for electrons right?

Yes, you are right.

**Comment by henry2004y** [comment]
I think in the current implementation, `trace_normalization!` does not contain any coefficient. All the normalizations are handled by the user, for example in the [Dimensionless Demo](https://henry2004y.github.io/TestParticle.jl/dev/examples/basics/demo_dimensionless/#demo_dimensionless). In `trace_relativistic_normalized!`, however, we do have $\omega$, but as reported in #198, this form is wrong and we will correct that later.

**Comment by Beforerr** [comment]
My hope is that the two interface would be united. Otherwise the user have to change code when change to `relativistic` algorithm because of different normalization.

Also it would be nice to have more flexible normalization (for example sometimes it is more useful to normalize velocity to  system characteristic velocity instead of speed of light)

**Comment by henry2004y** [comment]
Completed via #200
