### ISSUE TITLE
Compatibility with the latest version of OrdinaryDiffEq

### ISSUE THREAD

**Issue by TCLiuu** [henry2004y/TestParticle.jl#27]
After OrdinaryDiffEq 6.16.0, the `out of place` tracing function `trace` will incur an error `TypeNotConstantError` due to this [PR](https://github.com/SciML/OrdinaryDiffEq.jl/pull/1685).

The whole message:
```
ERROR: Detected non-constant types in an out-of-place ODE solve, i.e. for
`du = f(u,p,t)` we see `typeof(du) !== typeof(u/t)`. This is not
supported by OrdinaryDiffEq.jl's solvers. Please either make `f`
type-constant (i.e. typeof(du) === typeof(u/t)) or use the mutating
in-place form `f(du,u,p,t)` (which is type-constant by construction).

Note that one common case for this is when computing with GPUs, using
`Float32` for `u0` and `Float64` for `tspan`. To correct this, ensure
that the element type of `tspan` matches the preferred compute type,
for example `ODEProblem(f,0f0,(0f0,1f0))` for `Float32`-based time.

typeof(u/t) = Vector{Float64}
typeof(du) = SVector{6, Float64}
```

`trace`:
```julia
function trace(y, p, t)
   q, m, E, B = p
   dx, dy, dz = y[4:6]
   dux, duy, duz = q/m*(E(y) + y[4:6] × (B(y[1:3])))
   SVector{6}(dx, dy, dz, dux, duy, duz)
end
```

The point is the difference between the types of y and dy, but u0 cannot be a SArray that will throw another error.

What is the influence of non-constant types? And how to solve it? I have two ideas:
1. Changing the type of returned array.
2. Restricting the version of OrdinaryDiffEq.

**Comment by henry2004y** [comment]
Can we simply modify the initial types to `SArray`?

**Comment by TCLiuu** [comment]
The type of initial condition for `in place` function cannot be `SArray`. And the type of initial condition for `out of  place` function must be `SArray`.

**Comment by TCLiuu** [comment]
The latest version of OrdinaryDiffEq may have performance regession. Other variates like the version of other packages were controlled.

OrdinaryDiffEq v6.11.2  Meshes v0.19.6 StaticArrays v1.5.0
| ID                                             | time           | GC time | memory         | allocations |
|------------------------------------------------|---------------:|--------:|---------------:|------------:|
| `["trace", "analytic field", "in place"]`      |  8.886 μs (5%) |         | 33.36 KiB (1%) |         284 |
| `["trace", "analytic field", "out of place"]`  |  8.516 μs (5%) |         | 31.73 KiB (1%) |         268 |
| `["trace", "numerical field", "in place"]`     | 24.606 μs (5%) |         | 35.09 KiB (1%) |         285 |
| `["trace", "numerical field", "out of place"]` | 24.416 μs (5%) |         | 33.52 KiB (1%) |         268 |

OrdinaryDiffEq v6.18.1 Meshes v0.19.6 StaticArrays v1.5.0
| ID                                             | time           | GC time | memory         | allocations |
|------------------------------------------------|---------------:|--------:|---------------:|------------:|
| `["trace", "analytic field", "in place"]`      | 11.060 μs (5%) |         | 34.48 KiB (1%) |         297 |
| `["trace", "analytic field", "out of place"]`  | 10.640 μs (5%) |         | 32.94 KiB (1%) |         281 |
| `["trace", "numerical field", "in place"]`     | 31.419 μs (5%) |         | 53.53 KiB (1%) |         329 |
| `["trace", "numerical field", "out of place"]` | 30.507 μs (5%) |         | 51.12 KiB (1%) |         313 |

**Comment by henry2004y** [comment]
This is kind of strange. Can you check again with PR #29?

**Comment by TCLiuu** [comment]
This problem still exists.

OrdinaryDiffEq v6.11.2 Meshes v0.19.6 StaticArrays v1.5.0
| ID                                                  | time           | GC time | memory         | allocations |
|-----------------------------------------------------|---------------:|--------:|---------------:|------------:|
| `["trace", "analytic field", "in place"]`           |  6.336 μs (5%) |         | 18.59 KiB (1%) |         149 |
| `["trace", "analytic field", "out of place"]`       |  5.415 μs (5%) |         | 16.97 KiB (1%) |         133 |
| `["trace", "numerical field", "in place"]`          | 21.560 μs (5%) |         | 20.31 KiB (1%) |         149 |
| `["trace", "numerical field", "out of place"]`      | 21.851 μs (5%) |         | 18.75 KiB (1%) |         133 |
| `["trace", "time-dependent field", "in place"]`     |  7.707 μs (5%) |         | 20.28 KiB (1%) |         165 |
| `["trace", "time-dependent field", "out of place"]` |  6.620 μs (5%) |         | 18.64 KiB (1%) |         148 |

OrdinaryDiffEq v6.18.1 Meshes v0.19.6 StaticArrays v1.5.0
| ID                                                  | time           | GC time | memory         | allocations |
|-----------------------------------------------------|---------------:|--------:|---------------:|------------:|
| `["trace", "analytic field", "in place"]`           |  9.718 μs (5%) |         | 19.78 KiB (1%) |         167 |
| `["trace", "analytic field", "out of place"]`       |  8.827 μs (5%) |         | 18.23 KiB (1%) |         151 |
| `["trace", "numerical field", "in place"]`          | 29.925 μs (5%) |         | 39.75 KiB (1%) |         199 |
| `["trace", "numerical field", "out of place"]`      | 29.345 μs (5%) |         | 37.34 KiB (1%) |         183 |
| `["trace", "time-dependent field", "in place"]`     | 13.065 μs (5%) |         | 21.52 KiB (1%) |         186 |
| `["trace", "time-dependent field", "out of place"]` | 11.752 μs (5%) |         | 19.97 KiB (1%) |         170 |

```
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
      Ubuntu 18.04.5 LTS
  uname: Linux 5.4.0-80-generic #90~18.04.1-Ubuntu SMP Tue Jul 13 19:40:02 UTC 2021 x86_64 x86_64
  CPU: AMD Ryzen 7 3800X 8-Core Processor: 
                 speed         user         nice          sys         idle          irq
       #1-16  1902 MHz   41404676 s      79707 s    2862567 s  1334491249 s          0 s
       
  Memory: 31.78772735595703 GB (15861.92578125 MB free)
  Uptime: 8.633145e6 sec
  Load Avg:  1.04  0.64  0.41
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
```

**Comment by henry2004y** [comment]
There is currently no compatibility issue, but maybe some performance regressions. However, there is no reason for us to stick to an old version of OrdinaryDiffEq (the current version is v6.29.3). If we want to squeeze out the ultimate performance, we shall contribute to OrdinaryDiffEq directly.

**Comment by TCLiuu** [comment]
When I run the benchmarks via `results = benchmarkpkg(TestParticle)`, I get

| ID                                                  | time           | GC time | memory         | allocations |
|-----------------------------------------------------|---------------:|--------:|---------------:|------------:|
| `["trace", "analytic field", "in place"]`           |  7.163 μs (5%) |         | 14.02 KiB (1%) |         157 |
| `["trace", "analytic field", "out of place"]`       |  5.938 μs (5%) |         | 12.31 KiB (1%) |         133 |
| `["trace", "numerical field", "in place"]`          | 24.084 μs (5%) |         | 27.08 KiB (1%) |         175 |
| `["trace", "numerical field", "out of place"]`      | 20.708 μs (5%) |         | 21.45 KiB (1%) |         147 |
| `["trace", "time-dependent field", "in place"]`     |  8.493 μs (5%) |         | 15.22 KiB (1%) |         172 |
| `["trace", "time-dependent field", "out of place"]` |  7.145 μs (5%) |         | 13.52 KiB (1%) |         148 |

**Comment by henry2004y** [comment]
Looks like it changes a lot between different versions...
