### ISSUE TITLE
The equations of motion in `trace_relativistic` are not correct.

### ISSUE THREAD

**Issue by TCLiuu** [henry2004y/TestParticle.jl#34]
When I attempted to solve those problems mentioned by #25, I found the equations of motion in `trace_relativistic` are wrong.

The equations of motion in `trace_relativistic` are: 

$$
\frac{\mathrm{d}\mathbf{v}}{\mathrm{d}t} = \frac{q}{\gamma m}(\mathbf{E}+\mathbf{v}\times\mathbf{B}),
$$

where $\gamma = 1/\sqrt{1-v^2/c^2}$.

These equations are not Lorentz covariant. The equations of motion based on four-momentum should be written as:

$$
\frac{\mathrm{d}p^\mu}{\mathrm{d}\tau} = \gamma q(E^\mu+\epsilon_{\mu \nu l}v^\nu B^l),
$$

where $\tau$ is proper time and $p^\mu = \gamma m v^\mu$. These equations are Lorentz covariant. And after a simplification, they can be written as:

$$
\frac{\mathrm{d}(\gamma v^\mu)}{\mathrm{d}t} = \frac{q}{m}(E^\mu+\epsilon_{\mu \nu l}v^\nu B^l), \tag{1}
$$

or

$$
\frac{\mathrm{d}v^\mu}{\mathrm{d}t} = \frac{q}{m \gamma^3}(E^\mu+\epsilon_{\mu \nu l}v^\nu B^l). \tag{2}
$$

And, I have found the accuracy of  Eq.(1) in numerical calculation is better than Eq.(2).

**Comment by henry2004y** [comment]
That's a nice check! Could you share a reference to the equations?

**Comment by TCLiuu** [comment]
> That's a nice check! Could you share a reference to the equations?

You can see https://en.wikipedia.org/wiki/Four-force or Jackson's _Classical Electrodynamics 3rd_  chapter 11.9. It can be derived directly from the equations of motion based on four-momentum.

**Comment by henry2004y** [comment]
I have a question about the current choice of Eq.(2) over Eq.(1) @TCLiuu: Could you remind me of the reasons behind this choice?
