### ISSUE TITLE
Support 2D fields

### ISSUE THREAD

**Issue by henry2004y** [henry2004y/TestParticle.jl#41]
The current method
https://github.com/henry2004y/TestParticle.jl/blob/fc24ec7e39296c4be5476e4ea639ad25ba570cbb/src/TestParticle.jl#L42

only supports 3D fields. In some cases, it may be useful to assume periodic boundaries in the out-of-plane direction and only provide 2D fields, e.g. a 2D MHD simulation with outputs of B and V on a plane.

**Comment by TCLiuu** [comment]
ALL plot recipes are based on the assumption that the solution has six dimension. Should we support the solutions with 2D field in TestParticleMakie?

**Comment by henry2004y** [comment]
Good catch. When I added the 2D field support, I thought a bit about the possibility of keeping the third spatial dimension but simply making it all 0s. Then there will be no issues for the plotting recipes. However, putting all 0s may be a misleading point, because particles can still move in the out-of-plane direction. Now I realize that I should keep updating z as well even though the field looks 2D, because the underlying assumption is that it is a periodic in the out-of-plane direction.

**Comment by henry2004y** [comment]
Now we are consistent with all 6D outputs in #42.
