### ISSUE TITLE
Precompilation

### ISSUE THREAD

**Issue by henry2004y** [henry2004y/TestParticle.jl#43]
Add usage of [SnoopPrecompile](https://timholy.github.io/SnoopCompile.jl/dev/snoop_pc/).

**Comment by TCLiuu** [comment]
What is the purpose of this package? 
> It does 3 things:
> 1. run the block only when precompilling (it incorporates if ccall(:jl_generating_output, Cint, ()) == 1) so that if you’re running with --compiled-modules=no you don’t waste time
> 2. disables the interpreter when running the block (to ensure everything gets compiled)
> 3. intercept runtime dispatch to force precompilation of calls to methods defined in other packages

But I do not understand what it will improve. Can this package accelerate the first plot of TestParticleMakie?

**Comment by henry2004y** [comment]
The basic idea is to cache the inferred low level code (*.jl) in the precompiled file to reduce the work in first-time-to-X. I think it can improve the first time to plot with Makie, since we already depend on Makie. Note that In #46 I did not include anything calling OrdinaryDiffEq because currently we do not directly depend on OrdinaryDiffEq.
