### ISSUE TITLE
Support multiple particles in `TestParticleMakie`

### ISSUE THREAD

**Issue by TCLiuu** [henry2004y/TestParticle.jl#47]
`TestParticleMakie` does not support `EnsembleProblem`.

**Comment by henry2004y** [comment]
Here is a temporary workaround as described in `plotfunctions.md`:

```julia
f = Figure()
ax = Axis3(f[1,1])
for i in eachindex(sol)
    lines!(sol[i], label="$i")
end
Legend(f[1,2], ax, nbanks=1, label=L"p")
f
```

Do we need a new method for plotting `EnsembleProblem`? Maybe this is already good enough?

**Comment by TCLiuu** [comment]
> 

It is a solution, but those interactive plot recipes cannot support `EnsembleProblem` like this.
