### ISSUE TITLE
Register TestParticleMakie

### ISSUE THREAD

**Issue by henry2004y** [henry2004y/TestParticle.jl#49]
@TCLiuu, would you like to try registering TestParticleMakie v0.1? See the instructions [here](https://github.com/JuliaRegistries/Registrator.jl).

**Comment by TCLiuu** [comment]
@JuliaRegistrator register subdir=TestParticleMakie/

**Comment by henry2004y** [comment]
There are some issues to be fixed. See the link above.

**Comment by TCLiuu** [comment]
@JuliaRegistrator register subdir=TestParticleMakie

**Comment by TCLiuu** [comment]
@JuliaRegistrator register subdir=TestParticleMakie

**Comment by TCLiuu** [comment]
> There are some issues to be fixed. See the link above.

There should be no slash at the end of the "subdir" keyword. : (
