### ISSUE TITLE
Diamagnetic drift

### ISSUE THREAD

**Issue by henry2004y** [henry2004y/TestParticle.jl#60]
From fluid theory, there is a so-called [diamagnetic drift](https://henry2004y.github.io/KeyNotes/fluid-drifts-perpendicular-to-b) that is never discussed in the single particle motion section. This is another case where a drift occurs even though the guiding centers are stationary (besides the polarization drift).

Diamagnetic drift can also lead to a current because of the dependence on charge $q$. This, however, is not so obvious from a single particle point of view since the guiding centers do not drift. Are we able to demonstrate this via a test particle model?

**Comment by TCLiuu** [comment]
Diamagnetic drift is a collective effect, we cannot find it in the Lagrangian of a charged particle or the guiding center. If we want to demonstrate this drift, maybe we can abstract the effect of gradient as a body force field.

**Comment by henry2004y** [comment]
Maybe some setup like Figure 7 in [this note](https://farside.ph.utexas.edu/teaching/plasma/lectures1/node39.html). But I am not exactly sure how we want to demonstrate this: should we simply launch more particles on the right and computing some averging, or introduce an additional $\nabla p$ force?

**Comment by TCLiuu** [comment]
> Diamagnetic drift is a collective effect, we cannot find it in the Lagrangian of a charged particle or the guiding center. If we want to demonstrate this drift, maybe we can abstract the effect of gradient as a body force field.

Sorry, I think my idea is wrong, we cannot replace a collective effect with an additional force. A drift with a force field is far different from a collective effect.

**Comment by henry2004y** [comment]
So to conclude, the diamagnetic drift is a macroscopic effect that does not appear in the single particle motion.
